# Generated by Django 2.1.15 on 2019-12-18 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nid', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('ntype', models.CharField(max_length=100)),
                ('time', models.DateField()),
                ('content', models.CharField(max_length=2000)),
                ('staff_id', models.IntegerField()),
                ('image', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'news',
            },
        ),
        migrations.CreateModel(
            name='NewsObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('ntype', models.CharField(max_length=100)),
                ('time', models.DateField()),
                ('content', models.CharField(max_length=2000)),
                ('staff_id', models.IntegerField()),
            ],
        ),
    ]
